### ISSUE TITLE
Doesn't work when the language is set to TypeScript

### ISSUE THREAD

**Issue by ermik** [enotramone/atom-webdriverio-snippets#2]
This is a bug.

Expected:
Snippets would appear in the entire family of JS languages, in other words, whenever they are legal.

Actual:
No snippets appear when language is set to TypeScript

Reproduce:
Set language to TypeScript or make a `.ts` file and attempt to trigger snippets.

**Comment by adequatica** [comment]
Hello,
Thanks for the report!
I made support of TypeScript files in [the latest update](https://github.com/enotramone/atom-webdriverio-snippets/releases/tag/v0.5.0), please, update your Atom packages.
